### ISSUE TITLE
[Dados] Refatoração de acordo com o modelos da parte de entrada do console

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#1]
Criar a interface e classes representadas na figura. A interface IRecebedorDados sera usada na classe EntradaDeDados

![Image](https://user-images.githubusercontent.com/37370490/216439100-8fb79859-c7f4-4ce2-b132-4d668f81daf1.png)

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
