### ISSUE TITLE
Implemetar classes de mensagem de View

### ISSUE THREAD

**Issue by Blarissa** [Blarissa/ResidencialIUUL#16]
Implementar classes da camada View e atualizar documentação do código
- [Classe MenssagemDeErro](https://github.com/Blarissa/ResidencialIUUL/blob/main/Desafio3/Desafio/View/Mensagens/MenssagemDeErro.cs)
- [Classe MenssagemDeSucesso](https://github.com/Blarissa/ResidencialIUUL/blob/main/Desafio3/Desafio/View/Mensagens/MenssagemDeSucesso.cs)

![Image](https://user-images.githubusercontent.com/54214827/216154337-f5dad2fb-42bb-4319-ad51-0d9b7d302fc6.png)

**Comment by JevsJevs** [comment]
Serão usadas pela classe EntradaDeDados, que é um controller
