### ISSUE TITLE
Implementar métodos de interfaces nos modelos

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#2]
Implementar métodos referentes a interfaces de c#.

**Classe Modelo Consulta.**
IAComparable -> Equals
IAGetHashCode -> GetHashCode
Override de ToString

**Classe Modelo Paciente.**
IAComparable -> Equals
IAGetHashCode -> GetHashCode
Override de ToString

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
