### ISSUE TITLE
Atualizar o uso do método Paciente Existe no PacienteController

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#4]
O seguinte método está localizado no arquivo PacienteController da pasta Desafio.Controllers
![Image](https://user-images.githubusercontent.com/37370490/214370706-92fe2d80-c33e-4e25-98c8-c801ce7e2d6b.png)

Para manter conformidade com o modelo utilizar o método do ValidaController(coberto pela task #2)

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
