### ISSUE TITLE
Criar a classe "PacienteDAO" para comunicar com o banco de dados

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#5]
Essa classe deve existir para ter como objetivo conter a lógica de conexão com o BD escolhido

Ela deverá ser capaz de retornar a "ListaDePacientes" que entendiamos como o BD previamente. 

O modelo dessa classe se assemelha a isso:

![Image](https://user-images.githubusercontent.com/37370490/214392376-a72723f3-c1dc-4849-8424-367b463a819f.png)

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
