### ISSUE TITLE
Atualizar o uso do método ConsultaExiste no AgendaController

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#7]
De forma semelhante com o #4 é preciso desacoplar a Consulta, colocando um método para isso no **ValidaController**

Para manter a responsabilidade única crie uma classe AgendaDAO para comunicar com o BD e fornecer ao método ExisteConsulta(recém criado no ValidaController) a lista de Consultas

![Image](https://user-images.githubusercontent.com/37370490/214377165-965f2673-551d-4bd9-9d7c-b8d39f2b1033.png)

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
