### ISSUE TITLE
Implementação na classe ConsultaDAO

### ISSUE THREAD

**Issue by JevsJevs** [Blarissa/ResidencialIUUL#9]
Implementar classe

- [ConsultaDAO](https://github.com/Blarissa/ResidencialIUUL/blob/main/Desafio3/Desafio/Data/DAO/ConsultaDAO.cs)

![Image](https://user-images.githubusercontent.com/54214827/216442025-0749ec35-6bff-4a12-9913-a5eca214d088.png)

**Comment by Blarissa** [comment]
E atualizar documentação do código se necessário
